# Generated by Django 5.0.2 on 2024-02-17 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_alter_comment_modified_date_alter_comment_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='modified_date',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
