# Generated by Django 5.0.2 on 2024-02-17 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_alter_post_modified_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='modified_date',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
