# Generated by Django 5.0.2 on 2024-02-18 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_alter_comment_modified_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_answered',
            field=models.BooleanField(default=False),
        ),
    ]
