# Generated by Django 5.0.2 on 2024-02-19 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_tag_alter_comment_modified_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='post',
            name='is_answered',
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('approved', 'Onaylanmış'), ('rejected', 'Reddedilmiş'), ('pending', 'Beklemede')], default='pending', max_length=20),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
